

variables:
  GIT_SUBMODULE_STRATEGY: none

update_website:
  stage: build
  image: python:3.7
  script:
    - python -m	pip install -r requirements.txt
    - python scripts/ggi_update_website.py
    - git config user.email gitlab@my-ggi.com
    - git config user.name "GitLab pipeline"
    - git commit -m "[skip ci] Update website." -a


pages:
  stage: deploy
  # All available Hugo versions are listed here:
  # https://gitlab.com/pages/hugo/container_registry
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  script:
    - cd web && hugo && cd -
    - mv -v web/public .
  artifacts:
    paths:
      - public/
  only:
    - main
