

variables:
  GIT_SUBMODULE_STRATEGY: none

update_website:
  stage: build
  image: python:3.7
  script:
    - python -m	pip install -r requirements.txt
    - python scripts/ggi_update_website.py
  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
    paths:
      - ./web

pages:
  stage: deploy
  # All available Hugo versions are listed here:
  # https://gitlab.com/pages/hugo/container_registry
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  script:
    - cd web && hugo && cd -
    - mv -v web/public .
  cache:
    key: "$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
    paths:
      - ./web
  artifacts:
    paths:
      - public/
  only:
    - main
