
name: My GGI Deploy deployment
run-name: Deploying your own GGI!
on:
  push:
    branches:
      - main
jobs:
  Update website:
    name: Update website
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install depencies
        run: |
	  python -m pip install -r requirements.txt
      - name: GGI Deploy
        run: |
	  python scripts/ggi_deploy.py -a -b -d -p
      - name: GGI Update website
        run: |
	  python scripts/ggi_update_website.py

